import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Bolt,
  Box,
  Boxes,
  Building2,
  Car,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  Dumbbell,
  Eye,
  EyeOff,
  Factory,
  Flag,
  Globe2,
  Heart,
  HeartPulse,
  House,
  Link,
  Lock,
  Menu,
  MessageCircle,
  MessageSquare,
  Microchip,
  Package,
  PackageOpen,
  RotateCcw,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Star,
  Trash2,
  Truck,
  User,
  X,
  ZoomIn,
} from 'lucide-react';

const icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  badgeCheck: BadgeCheck,
  bars: Menu,
  bolt: Bolt,
  box: Box,
  boxes: Boxes,
  building: Building2,
  car: Car,
  cart: ShoppingCart,
  cartAdd: ShoppingCart,
  cartDownload: ShoppingCart,
  certificate: BadgeCheck,
  chartLine: BarChart3,
  check: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleAlert: CircleAlert,
  circleCheck: CheckCircle2,
  circleQuestion: CircleHelp,
  commentDots: MessageCircle,
  dumbbell: Dumbbell,
  eye: Eye,
  eyeOff: EyeOff,
  facebook: MessageCircle,
  fileInvoice: Package,
  fileInvoiceDollar: Package,
  flag: Flag,
  globe: Globe2,
  heart: Heart,
  heartPulse: HeartPulse,
  headset: MessageSquare,
  house: House,
  industry: Factory,
  link: Link,
  lock: Lock,
  magnifyPlus: ZoomIn,
  message: MessageCircle,
  microchip: Microchip,
  paperPlane: Send,
  packageOpen: PackageOpen,
  phone: MessageCircle,
  rotateLeft: RotateCcw,
  search: Search,
  share: Share2,
  shield: ShieldCheck,
  shirt: Shirt,
  shoppingBasket: ShoppingBasket,
  star: Star,
  thLarge: Boxes,
  times: X,
  trash: Trash2,
  truck: Truck,
  truckFast: Truck,
  user: User,
  whatsapp: MessageCircle,
  xTwitter: X,
};

export default function Icon({ name, size = 16, className = '', strokeWidth = 2.25, ...props }) {
  const LucideIcon = icons[name] || CircleHelp;

  return (
    <LucideIcon
      aria-hidden="true"
      className={`inline-block shrink-0 align-[-0.125em] ${className}`}
      size={size}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
